### ISSUE TITLE
[BUG] PythonPyLammps test fails on Fedora

### ISSUE THREAD

**Issue by junghans** [lammps/lammps#2380]
**Summary**

Try to build lammps 20200918 on Fedora and the PythonPyLammps test fails

**LAMMPS Version and Platform**

Fedora Rawhide

**Expected Behavior**

Test passed

**Actual Behavior**

```
6/30 Test #30: PythonPyLammps ...................***Failed    0.13 sec
test_create_atoms (__main__.PythonPyLammps) ... ERROR
test_runs (__main__.PythonPyLammps) ... ERROR
test_version (__main__.PythonPyLammps) ... ok
test_write_script (__main__.PythonPyLammps) ... ok
======================================================================
ERROR: test_create_atoms (__main__.PythonPyLammps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/unittest/python/python-pylammps.py", line 50, in test_create_atoms
    self.assertEqual(self.pylmp.system.natoms, 2)
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/python/lammps.py", line 2247, in system
    d = self._parse_info_system(output)
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/python/lammps.py", line 2343, in _parse_info_system
    lines = output[6:-2]
TypeError: 'NoneType' object is not subscriptable
======================================================================
ERROR: test_runs (__main__.PythonPyLammps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/unittest/python/python-pylammps.py", line 76, in test_runs
    self.pylmp.run(10)
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/python/lammps.py", line 2213, in run
    self.runs += get_thermo_data(output)
  File "/builddir/build/BUILD/lammps-patch_18Sep2020/python/lammps.py", line 2056, in get_thermo_data
    for line in lines:
TypeError: 'NoneType' object is not iterable
----------------------------------------------------------------------
Ran 4 tests in 0.044s
FAILED (errors=2)
```
build log attached

**Steps to Reproduce**

Build and run tests on Fedora Rawhide

**Further Information, Files, and Links**

[build.log.zip](https://github.com/lammps/lammps/files/5250627/build.log.zip)

**Comment by rbberger** [comment]
That means there is something buffering stdout.

**Comment by rbberger** [comment]
Ok, I think I found the issue.

**Comment by rbberger** [comment]
@junghans let me know if 61ce732 fixes this for you

**Comment by junghans** [comment]
Running https://koji.fedoraproject.org/koji/taskinfo?taskID=51893852

**Comment by junghans** [comment]
Now a different test (`PythonOpen`) fails later:
```
26: Create LAMMPS instance without any arguments ... LAMMPS (18 Sep 2020)
26: OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:94)
26:   using 1 OpenMP thread(s) per MPI task
26: FAIL
26: Total wall time: 0:00:00
26: testWithArgs (__main__.PythonOpen)
26: Create LAMMPS instance with a few arguments ... LAMMPS (18 Sep 2020)
26: OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:94)
26:   using 1 OpenMP thread(s) per MPI task
26: Total wall time: 0:00:00
26: ok
26: testWithMPI (__main__.PythonOpen) ... skipped 'Skipping MPI test since LAMMPS is not parallel or mpi4py is not found'
26:
26: ======================================================================
26: FAIL: testNoArgs (__main__.PythonOpen)
26: Create LAMMPS instance without any arguments
26: ----------------------------------------------------------------------
26: Traceback (most recent call last):
26:   File "/builddir/build/BUILD/lammps-patch_18Sep2020/unittest/python/python-open.py", line 35, in testNoArgs
26:     self.assertEqual(has_mpi,lmp.has_mpi_support)
26: AssertionError: False != True
26:
26: ----------------------------------------------------------------------
26: Ran 3 tests in 0.051s
26:
26: FAILED (failures=1, skipped=1)
```
[build.log.zip](https://github.com/lammps/lammps/files/5252030/build.log.zip)

Maybe mpi4py is missing to just this test?

**Comment by junghans** [comment]
Testing with `mpi4py` installed: https://koji.fedoraproject.org/koji/taskinfo?taskID=51900056.

Anyhow, if this the problem we should check if the `mpi4py` module is available somewhere in CMake.

**Comment by junghans** [comment]
Nope, even with `mpi4py` installed, it still fails.

[mpi4py.log.zip](https://github.com/lammps/lammps/files/5252542/mpi4py.log.zip)

**Comment by junghans** [comment]
This issue also happens on `x86_64` and other plattforms.

**Comment by rbberger** [comment]
The logic in the test is wrong.

```
lmp = lammps()
has_mpi = lmp.has_mpi_support  

lmp2 =lammps(name="mpich")
has_mpi2 = lmp2.has_mpi_support
```

`has_mpi` doesn't have to be the same as `has_mpi2`.

**Comment by rbberger** [comment]
See 7d07d04989e0063c920e4ec08d2798f739375c7c

**Comment by junghans** [comment]
Testing: https://koji.fedoraproject.org/koji/taskinfo?taskID=51916106

**Comment by junghans** [comment]
Success on i686 for now.

**Comment by junghans** [comment]
Works thanks! Lammps version bump in process now: https://koji.fedoraproject.org/koji/taskinfo?taskID=51933946
