### ISSUE TITLE
[BUG]`tools/replica/reorder_remd_traj.py` can't find `byteind_1.gz` because of wrong indent

### ISSUE THREAD

**Issue by yihengwuKP** [lammps/lammps#3026]
**Summary**

Running the `example` folder under `tools/replica` resulted in errors of `byteind_1.gz` not found. This is caused by the indent of the `return`, currently it is inside the for loop.

**LAMMPS Version and Platform**
tag: stable_29Sep2021_update1, (result of `git clone git@github.com:lammps/lammps.git`)
Linux platform

**Expected Behavior**

The python script should read through the remd trajectory and parse it into the hidden file `.byteind_<num>.gz`, then the hidden files will be loaded and reordered the into constant temperature trajectories.

**Actual Behavior**

The script failed to write `.byteind_1.gz` and the following other gz files, and throw `OSError`
```bash
Getting frames from all replicas at temperature:
200.00 K
209.00 K
219.00 K
230.00 K
241.00 K
252.00 K
264.00 K
276.00 K
289.00 K
303.00 K
317.00 K
332.00 K
348.00 K
365.00 K
382.00 K
400.00 K
Reading replicas: 100B/replica [00:00, 107B/replica/s]
Traceback (most recent call last):
  File "../reorder_remd_traj.py", line 523, in <module>
    byte_inds = dict( (i, np.loadtxt(fn)) for i, fn in enumerate(byteindfns) )
  File "../reorder_remd_traj.py", line 523, in <genexpr>
    byte_inds = dict( (i, np.loadtxt(fn)) for i, fn in enumerate(byteindfns) )
  File "/home/yihengwu917/.conda/envs/analysis/lib/python3.7/site-packages/numpy/lib/npyio.py", line 961, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/yihengwu917/.conda/envs/analysis/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 195, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/yihengwu917/.conda/envs/analysis/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 535, in open
    raise IOError("%s not found." % path)
OSError: /home/yihengwu917/source_code/lammps/tools/replica/example/output/.byteind_3.gz not found.
```

**Steps to Reproduce**

```bash
1. git clone git@github.com:lammps/lammps.git
2. cd lammps/tools/replica/example
3. mpirun -np 16 lmp_mpi -partition 16x1 -in in.peptide -log log.peptide
4. python parse_ene.py temps.txt log.peptide
5. python ../reorder_remd_traj.py peptide -logfn log.peptide -tfn temps.txt -ns 10 -nw 20 -np 1000 -ot 200 276 400 -logw -e ene.peptide -od ./output
```
(In step 3, I used lmp_mpi that's built under version `lammps-stable_7Aug2019`, and with packages `MOLECULE`, `KSPACE` and `REPLICA`, but it doesn't matter much since this step it runs smoothly.) Basically this means the `reorder_remd_traj.py` couldn't run through its own example.

**Further Information, Files, and Links**
After a bit debugging, I actually found what I think the problem is: in line 209, the `return should only have one tab depth of indent, but now it has two tab depth of indent, which makes it inside the for loop:

```python
152 def get_byte_index(rep_inds, byteindfns, intrajfns):
153     """
154     Get byte indices from (un-ordered) trajectories.
155 
156     :param rep_inds: indices of replicas to process on this proc
157 
158     :param byteindsfns: list of filenames that will contain the byte indices
159 
160     :param intrajfns: list of (unordered) input traj filenames
161     """
162     for n in rep_inds:
163         # check if the byte indices for this traj has already been computed
164         if os.path.isfile(byteindfns[n]): continue
165 
166         # extract bytes
167         fobj = readwrite(intrajfns[n], "rb")
168         byteinds = [ [0,0] ]
169 
170         # place file pointer at first line
171         nframe = 0
172         first_line = fobj.readline()
173         cur_pos = fobj.tell()
174 
175         # status printed only for replica read on root proc
176         # this assumes that each proc takes roughly the same time
177         if me == ROOT:
178             pb = tqdm(desc = "Reading replicas", leave = True,
179                   position = ROOT + 2*me,
180                   unit = "B/replica", unit_scale = True,
181                   unit_divisor = 1024)
182 
183         # start crawling through the bytes
184         while True:
185             next_line = fobj.readline()
186             if len(next_line) == 0: break
187             # this will only work with lammpstrj traj format.
188             # this condition essentially checks periodic recurrences
189             # of the token TIMESTEP. Each time it is found,
190             # we have crawled through a frame (snapshot)
191             if next_line == first_line:
192                 nframe += 1
193                 byteinds.append( [nframe, cur_pos] )
194                 if me == ROOT: pb.update()
195             cur_pos = fobj.tell()
196             if me == ROOT: pb.update(0)
197         if me == ROOT: pb.close()
198 
199         # take care of the EOF
200         cur_pos = fobj.tell()
201         byteinds.append( [nframe+1, cur_pos] ) # dummy index for the EOF
202 
203         # write to file
204         np.savetxt(byteindfns[n], np.array(byteinds), fmt = "%d")
205 
206         # close the trajfile object
207         fobj.close()
208 
209         return

```

This explains why the process of writing the `.gz` file would stop after the 0 processor trajectory, because after written the 0 one, the function is directly returned! The fix would be very easy, just make it 1 tab indent. This can probably explain why this might not be found during the development, because once all the `.gz` hidden files are written, the function `get_byte_index` would just `pass` because of `os.path.isfile(byteindfns[n])` is true.

Another minor issue I found is, now the help section claims that the command line argument `-ot` has the default option as all the temperatures used in the simulation. But it is actually never set. If I ran `python ../reorder_remd_traj.py peptide -logfn log.peptide -tfn temps.txt -ns 10 -nw 20 -np 1000 -logw -e ene.peptide -od ./output` instead in the step 5 above, I would get following error:
```bash
Traceback (most recent call last):
  File "../reorder_remd_traj.py", line 481, in <module>
    for t in out_temps]
TypeError: 'NoneType' object is not iterable
```
This can be easily fixed by adding 
```python
460     # get (unordered) trajectories
461     temps = np.loadtxt(tempfn)
462     if not out_temps:
463         out_temps = temps
464     ntemps = len(temps)

```

After chaning accordingly, the scripts can run smoothly. I've incorporated the changes to the pull request here:

**Comment by yihengwuKP** [comment]
According to the history, maybe @tanmoy7989 and @akohlmey may know whether this makes sense or not!
