### ISSUE TITLE
USER-DPD fix_rx segfaults when input file is invalid

### ISSUE THREAD

**Issue by stanmoore1** [lammps/lammps#348]
USER-DPD fix_rx segfaults when its input file (such as kinetics.dpdrx) is invalid (for example, if there is a stray line). Ideally it should error out gracefully and notify the user the file is invalid without segfaulting.

<pre>
==129793== Invalid read of size 1
==129793==    at 0x4088098: strlen (vg_replace_strmem.c:454)
==129793==    by 0x1017C00B: LAMMPS_NS::FixRX::post_constructor() (fix_rx.cpp:319)
==129793==    by 0x10449587: LAMMPS_NS::Modify::add_fix(int, char**, int) (modify.cpp:900)
==129793==    by 0x10153083: fix (input.cpp:1559)
==129793==    by 0x10153083: LAMMPS_NS::Input::execute_command() (input.cpp:797)
==129793==    by 0x1015373B: LAMMPS_NS::Input::file() (input.cpp:244)
==129793==    by 0x100233B3: main (main.cpp:47)
==129793==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
<pre>

**Comment by stanmoore1** [comment]
@timattox

**Comment by akohlmey** [comment]
@stanmoore1 similar things can happen with many, if not most files that LAMMPS is reading, e.g. potential files. LAMMPS also doesn't check in many places, if fread() or fscanf() fails. 
What is often worse is, that in some cases LAMMPS will read incorrect/incomplete data and continue, if the file format is not properly matched.

**Comment by stanmoore1** [comment]
In this case I believe a one-line check for a NULL pointer would solve the problem. I just hate segfaults :)

**Comment by stanmoore1** [comment]
Perhaps we could add file checking/similar software quality improvements to our list of long-term improvement goals for LAMMPS.

**Comment by akohlmey** [comment]
i hate segfaults, too. but i hate file formats, that are not self-descriptive even more. i think this is an item for an in-depth developer discussion at the next LAMMPS workshop. this not only affects file reading, but also argument parsing, and there is a significant potential to make LAMMPS more resilient and maintainable as well as simplifying a lot of code and making it more consistent. ahhhh... one can always dream...

**Comment by akohlmey** [comment]
@timattox and @stanmoore1 is this still a valid issue?

**Comment by timattox** [comment]
AFAIK, this is still an open issue, but we can't work on it until after April 15th.

**Comment by joeweaver** [comment]
> @stanmoore1 similar things can happen with many, if not most files that LAMMPS is reading, e.g. potential files. LAMMPS also doesn't check in many places, if fread() or fscanf() fails.

I've been looking at fixing those sections up to get cleaner build logs, since they generate a lot of compiler warnings about unused return values.  Right now I'm just assigning the return value to an used variable.  I would be happy to do things The Right Way and  handle cases where the retval isn't correct based on what ferror()/feof() say.  Maybe wrap up the calls to a utility function.

Can't promise a time frame, based on the number of fread/fscanf calls I'm seeing, but happy to plug away as time permits.

**Comment by akohlmey** [comment]
> > @stanmoore1 similar things can happen with many, if not most files that LAMMPS is reading, e.g. potential files. LAMMPS also doesn't check in many places, if fread() or fscanf() fails.
> 
> I've been looking at fixing those sections up to get cleaner build logs, since they generate a lot of compiler warnings about unused return values. Right now I'm just assigning the return value to an used variable. I would be happy to do things The Right Way and handle cases where the retval isn't correct based on what ferror()/feof() say. Maybe wrap up the calls to a utility function.
> 
> Can't promise a time frame, based on the number of fread/fscanf calls I'm seeing, but happy to plug away as time permits.

@joeweaver thanks for your interest to help out. Please note that a lot of things have changed in the core LAMMPS code since this issue was posted and particularly since we switched to C++11 over a year ago and did some significant refactoring (which is still ongoing as time permits). We have a bunch of helpful [utility functions](https://docs.lammps.org/Developer_utils.html) and special purpose classes for redundant tasks like reading (potential) files or parsing text or values with validity checks (unlike atoi() or atof() and similar). This has been applied to a significant chunk of the core LAMMPS code and also parts of the packages.

**Comment by joeweaver** [comment]
Thanks for updating me on this, especially the pointer on the utility functions.  I believe I'm still seeing some bare calls to fread and such on an up-to-date source tree. (Example, variable.cpp line 715).  I'd be happy to fix these up using the util functions and submit PRs as I come across them.

**Comment by akohlmey** [comment]
> Thanks for updating me on this, especially the pointer on the utility functions. I believe I'm still seeing some bare calls to fread and such on an up-to-date source tree. (Example, variable.cpp line 715). I'd be happy to fix these up using the util functions and submit PRs as I come across them.

That specific use in the Variable class does not need updating, since it is reading a file that was just written and great care is taken to make certain the file is always present when it needs to be. Before that step has a chance to fail, other parts of LAMMPS will have failed already.

The utils namespace functions should be mostly needed when reading (binary) restart files.
For reading parameter or potential files, it is usually not worth the effort of updating those, since those should be refactored to use the (Potential)FileReader classes and then do the parsing with the ValueTokenizer class. If that is done well, then the amount of code required to read/parse a file will shrink substantially and the checks only need to be done in those classes and failures will be converted to exceptions. That also requires in some cases some code restructuring so that the reading is only done on MPI rank 0 and the parsed data then communicated (rather than broadcasting each line and parsing it on every MPI rank).

**Comment by joeweaver** [comment]
That make sense to me. It leaves a few compiler warnings during builds, but not the end of the world.

**Comment by jjramsey** [comment]
Is there a particular known input that triggered this segfault? It would help to have that to find how the segfault was triggered, or if it still even *could* be triggered given all the changes in LAMMPS since this bug was submitted.

**Comment by akohlmey** [comment]
> Is there a particular known input that triggered this segfault? It would help to have that to find how the segfault was triggered

@jjramsey how about you take an existing valid input and try all kinds of things to make it invalid? For example:
- add an incomplete line or remove required items from a line
- change a number to a non-numeric item
- use an invalid number
- use a string not matching a known identifier

and so on.

Please note that the parser in fix_rx.cpp is in dire need of a general refactor. For most of LAMMPS we have replaced parsers using `strtok()` and general C-style file and string handling  with the available file reader and tokenizer classes and C++ style strings where possible.  There are likely more parts of the DPD-REACT package, where this kind of change would be needed.

https://docs.lammps.org/latest/Developer_utils.html#file-reader-classes
https://docs.lammps.org/latest/Developer_utils.html#tokenizer-classes

>  or if it still even _could_ be triggered given all the changes in LAMMPS since this bug was submitted.

Given the modular nature of LAMMPS, this is rather unlikely. Please note that because of the complexity of some parts of the DPD-REACT code, it has been mostly skipped from general code updates.

**Comment by stanmoore1** [comment]
Yes this is still an issue:

```patch
diff --git a/examples/PACKAGES/dpd-react/dpdrx-shardlow/kinetics.dpdrx b/examples/PACKAGES/dpd-react/dpdrx-shardlow/kinetics.dpdrx
index ebc76294be..bcc569ce32 100644
--- a/examples/PACKAGES/dpd-react/dpdrx-shardlow/kinetics.dpdrx
+++ b/examples/PACKAGES/dpd-react/dpdrx-shardlow/kinetics.dpdrx
@@ -10,3 +10,4 @@
 1.0 hcn + 1.0 no2 = 1.0  no + 0.5 n2  + 0.5 h2 + 1.0 co   2.49081028001241E+01 0.0 1.344265387322009
 1.0 hcn + 1.0  no = 1.0  co + 1.0 n2  + 0.5 h2            4.98162056E+00 0.0 1.517718985686140
 1.0  no + 1.0  co = 0.5  n2 + 1.0 co2                     1.66054018667494E+06 0.0 6.938245245
+typo
```

```
LAMMPS (11 Feb 2026 - Development - patch_11Feb2026-232-g50ce71e2e0-modified)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff736e956 in __strcmp_evex () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff736e956 in __strcmp_evex () from /lib64/libc.so.6
#1  0x0000555555a19755 in LAMMPS_NS::FixRX::post_constructor (
    this=0x555555d9ef20) at ../fix_rx.cpp:282
#2  0x0000555555bad1a9 in LAMMPS_NS::Modify::add_fix(int, char**, int) [clone .constprop.0] (this=<optimized out>, narg=8, arg=0x555555d9ee20, trysuffix=1)
    at ../modify.cpp:948
#3  0x000055555566c403 in LAMMPS_NS::Input::fix (this=0x555555d403c0)
    at ../input.cpp:1574
#4  LAMMPS_NS::Input::execute_command (this=this@entry=0x555555d403c0)
    at ../input.cpp:811
#5  0x000055555566d6ef in LAMMPS_NS::Input::file (this=0x555555d403c0)
    at ../input.cpp:315
#6  0x000055555566565c in main (argc=<optimized out>, argv=<optimized out>)
    at ../main.cpp:66
(gdb) 
```
