### ISSUE TITLE
[BUG] 3 tests fail

### ISSUE THREAD

**Issue by yurivict** [lammps/lammps#3875]
**Summary**

2 tests fail in the testsuite.

**LAMMPS Version and Platform**
* stable_2Aug2023
* FreeBSD 13.2

**Actual Behavior**
```
        Start  20: FileOperations
 20/585 Test  #20: FileOperations .....................................Subprocess aborted***Exception:   0.40 sec
[==========] Running 10 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 10 tests from FileOperationsTest
[ RUN      ] FileOperationsTest.safe_fgets
[       OK ] FileOperationsTest.safe_fgets (14 ms)
[ RUN      ] FileOperationsTest.fgets_trunc
[       OK ] FileOperationsTest.fgets_trunc (1 ms)
[ RUN      ] FileOperationsTest.safe_fread
[       OK ] FileOperationsTest.safe_fread (2 ms)
[ RUN      ] FileOperationsTest.read_lines_from_file
[       OK ] FileOperationsTest.read_lines_from_file (1 ms)
[ RUN      ] FileOperationsTest.logmesg
[       OK ] FileOperationsTest.logmesg (1 ms)
[ RUN      ] FileOperationsTest.error_message_warn
[       OK ] FileOperationsTest.error_message_warn (1 ms)
[ RUN      ] FileOperationsTest.error_all_one
[       OK ] FileOperationsTest.error_all_one (2 ms)
[ RUN      ] FileOperationsTest.write_restart

[ FATAL ] /usr/ports/science/lammps/work/.build/_deps/googletest-src/googletest/src/gtest-port.cc:1155:: Only one stdout capturer can exist at a time.
[yv:80212] *** Process received signal ***
[yv:80212] Signal: Abort trap (6)
[yv:80212] Signal code:  (65543)
[yv:80212] [ 0] 0x82181f62c <pthread_sigmask+0x54c> at /lib/libthr.so.3
[yv:80212] [ 1] 0x82181ebd9 <pthread_setschedparam+0x839> at /lib/libthr.so.3
[yv:80212] [ 2] 0x7ffffffff2d3 <_fini+0x7fffffb84ee7> at ???
[yv:80212] [ 3] 0x829748d9a <__sys_thr_kill+0xa> at /lib/libc.so.7
[yv:80212] [ 4] 0x8296c1e64 <_raise+0x34> at /lib/libc.so.7
[yv:80212] [ 5] 0x829772809 <abort+0x49> at /lib/libc.so.7
[yv:80212] [ 6] 0x43c169 <_ZN7testing8internal5posix5AbortEv+0x9> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [ 7] 0x446897 <_ZN7testing8internal8GTestLogD2Ev+0xa7> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [ 8] 0x446977 <_ZN7testing8internalL13CaptureStreamEiPKcPPNS0_14CapturedStreamE+0x97> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [ 9] 0x42ca9a <_ZN10LAMMPSTest11HIDE_OUTPUTENSt3__18functionIFvvEEE+0x2a> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [10] 0x42bcf8 <_ZN18FileOperationsTest8TearDownEv+0x38> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [11] 0x47102e <_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+0x5e> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [12] 0x458199 <_ZN7testing8TestInfo3RunEv+0x109> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [13] 0x458c85 <_ZN7testing9TestSuite3RunEv+0x1f5> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [14] 0x46856f <_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x4ff> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [15] 0x471c7e <_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+0x5e> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [16] 0x468034 <_ZN7testing8UnitTest3RunEv+0x84> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] [17] 0x42517c <main+0x24c> at /usr/ports/science/lammps/work/.build/test_file_operations
[yv:80212] *** End of error message ***
```

```
 83/585 Test  #83: PythonCapabilities .................................***Failed    1.18 sec
test_accelerator_config (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok
test_available_id (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
fix charge all property/atom q ghost yes
region box block 0 1 0 1 0 1
create_box 1 box
Created orthogonal box = (0 0 0) to (1 1 1)
  1 by 1 by 1 MPI processor grid
group none empty
0 atoms in group none
variable test index 1
Total wall time: 0:00:00
ok
test_available_styles (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok
test_force_timeout (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
region box block 0 1 0 1 0 1
create_box 1 box
Created orthogonal box = (0 0 0) to (1 1 1)
  1 by 1 by 1 MPI processor grid
mass * 1.0
run 10
WARNING: No fixes with time integration, atoms won't move (src/verlet.cpp:60)
Setting up Verlet run ...
  Unit style    : lj
  Current step  : 0
  Time step     : 0.005
WARNING: No pairwise cutoff or binsize set. Atom sorting therefore disabled. (src/atom.cpp:2366)
WARNING: Communication cutoff is 0.0. No ghost atoms will be generated. Atoms may get lost. (src/comm_brick.cpp:210)
Per MPI rank memory allocation (min/avg/max) = 0.04702 | 0.04702 | 0.04702 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press     
         0   0              0              0              0              0            
        10   0              0              0              0              0            
Loop time of 1.9302e-05 on 1 procs for 10 steps with 0 atoms

Performance: 223811004.041 tau/day, 518081.028 timesteps/s, 0.000 atom-step/s
98.4% CPU use with 1 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 0          | 0          | 0          |   0.0 |  0.00
Neigh   | 0          | 0          | 0          |   0.0 |  0.00
Comm    | 2.111e-06  | 2.111e-06  | 2.111e-06  |   0.0 | 10.94
Output  | 8.396e-06  | 8.396e-06  | 8.396e-06  |   0.0 | 43.50
Modify  | 1.751e-06  | 1.751e-06  | 1.751e-06  |   0.0 |  9.07
Other   |            | 7.044e-06  |            |       | 36.49

Nlocal:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 0
Neighbor list builds = 0
Dangerous builds = 0
run 10
timer timeout off
New timer settings: style=normal  mode=nosync  timeout=off
run 10
WARNING: No fixes with time integration, atoms won't move (src/verlet.cpp:60)
Setting up Verlet run ...
  Unit style    : lj
  Current step  : 10
  Time step     : 0.005
WARNING: Communication cutoff is 0.0. No ghost atoms will be generated. Atoms may get lost. (src/comm_brick.cpp:210)
Per MPI rank memory allocation (min/avg/max) = 0.04702 | 0.04702 | 0.04702 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press     
        10   0              0              0              0              0            
        20   0              0              0              0              0            
Loop time of 1.6708e-05 on 1 procs for 10 steps with 0 atoms

Performance: 258558774.240 tau/day, 598515.681 timesteps/s, 0.000 atom-step/s
101.7% CPU use with 1 MPI tasks x 1 OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 0          | 0          | 0          |   0.0 |  0.00
Neigh   | 0          | 0          | 0          |   0.0 |  0.00
Comm    | 1.902e-06  | 1.902e-06  | 1.902e-06  |   0.0 | 11.38
Output  | 7.493e-06  | 7.493e-06  | 7.493e-06  |   0.0 | 44.85
Modify  | 1.466e-06  | 1.466e-06  | 1.466e-06  |   0.0 |  8.77
Other   |            | 5.847e-06  |            |       | 35.00

Nlocal:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Nghost:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0
Neighs:              0 ave           0 max           0 min
Histogram: 1 0 0 0 0 0 0 0 0 0

Total # of neighbors = 0
Neighbor list builds = 0
Dangerous builds = 0
Total wall time: 0:00:00
ok
test_gpu_device (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok
test_has_ffmpeg_support (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_has_gzip_support (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_has_id (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
fix charge all property/atom q ghost yes
region box block 0 1 0 1 0 1
create_box 1 box
Created orthogonal box = (0 0 0) to (1 1 1)
  1 by 1 by 1 MPI processor grid
group none empty
0 atoms in group none
variable test index 1
Total wall time: 0:00:00
ok
test_has_jpeg_support (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_has_package (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_has_png_support (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_has_style (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok
test_installed_packages (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
FAIL
test_is_running (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok
test_os_info (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
System: FreeBSD   LAMMPS OS Info: FreeBSD "FreeBSD 13.2-STABLE" 13.2-STABLE amd64
Clang C++ FreeBSD Clang 15.0.7 (https://github.com/llvm/llvm-project.git llvmorg-15.0.7-0-g8dfdcc7b7bf6) with OpenMP 5.0

Total wall time: 0:00:00
ok
test_version (__main__.PythonCapabilities) ... LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Total wall time: 0:00:00
ok

======================================================================
FAIL: test_has_ffmpeg_support (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 54, in test_has_ffmpeg_support
    self.assertEqual(self.lmp.has_ffmpeg_support, self.cmake_cache['WITH_FFMPEG'])
AssertionError: True != False

======================================================================
FAIL: test_has_gzip_support (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 45, in test_has_gzip_support
    self.assertEqual(self.lmp.has_gzip_support, self.cmake_cache['WITH_GZIP'])
AssertionError: True != False

======================================================================
FAIL: test_has_jpeg_support (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 51, in test_has_jpeg_support
    self.assertEqual(self.lmp.has_jpeg_support, self.cmake_cache['WITH_JPEG'])
AssertionError: True != False

======================================================================
FAIL: test_has_package (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 68, in test_has_package
    self.assertTrue(self.lmp.has_package(pkg))
AssertionError: False is not true

======================================================================
FAIL: test_has_png_support (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 48, in test_has_png_support
    self.assertEqual(self.lmp.has_png_support, self.cmake_cache['WITH_PNG'])
AssertionError: True != False

======================================================================
FAIL: test_installed_packages (__main__.PythonCapabilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/lammps/work/lammps-stable_2Aug2023/unittest/python/python-capabilities.py", line 61, in test_installed_packages
    self.assertIn(pkg, installed_packages)
AssertionError: 'CG-SDK' not found in ['ASPHERE', 'ATC', 'AWPMD', 'BOCS', 'BODY', 'BROWNIAN', 'CG-DNA', 'CLASS2', 'COLLOID', 'COLVARS', 'COMPRESS', 'DIELECTRIC', 'DIFFRACTION', 'DIPOLE', 'DPD-BASIC', 'DPD-MESO', 'DPD-REACT', 'DPD-SMOOTH', 'DRUDE', 'EFF', 'EXTRA-COMPUTE', 'EXTRA-DUMP', 'EXTRA-FIX', 'EXTRA-MOLECULE', 'EXTRA-PAIR', 'FEP', 'GRANULAR', 'H5MD', 'INTERLAYER', 'KIM', 'KOKKOS', 'KSPACE', 'LATBOLTZ', 'MACHDYN', 'MANIFOLD', 'MANYBODY', 'MC', 'MEAM', 'MGPT', 'MISC', 'ML-IAP', 'ML-RANN', 'ML-SNAP', 'MOFFF', 'MOLECULE', 'MOLFILE', 'MPIIO', 'NETCDF', 'ORIENT', 'PERI', 'PHONON', 'PLUGIN', 'PLUMED', 'POEMS', 'PTM', 'PYTHON', 'QEQ', 'QMMM', 'QTB', 'REACTION', 'REAXFF', 'REPLICA', 'RIGID', 'SHOCK', 'SMTBQ', 'SPH', 'SPIN', 'SRD', 'TALLY', 'UEF', 'VORONOI', 'VTK', 'YAFF']

----------------------------------------------------------------------
Ran 16 tests in 0.955s

FAILED (failures=6)
```

```
400/585 Test #400: AngleStyle:fourier .................................***Timeout 1500.03 sec
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from AngleStyle
[ RUN      ] AngleStyle.plain
```

**Steps to Reproduce**
regular testing

**Comment by akohlmey** [comment]
@yurivict please make certain that you delete your CMake cache and also note that you do not enable packages that have been removed or renamed. I can recall at least two cases: the LATTE package has been removed and CG-SDK rename to CG-SPICA. That should take care of the second failure.

**Comment by akohlmey** [comment]
@yurivict I cannot reproduce the test failures you are seeing.
CMake configuration summary:
```
-- <<< Build configuration >>>
   LAMMPS Version:   20230802
   Operating System: FreeBSD  
   CMake Version:    3.25.1
   Build type:       RelWithDebInfo
   Install path:     /home/akohlmey/.local
   Generator:        Ninja using /usr/local/bin/ninja
-- Enabled packages: AMOEBA;ASPHERE;BOCS;BODY;BPM;BROWNIAN;CG-DNA;CG-SPICA;CLASS2;COLLOID;COLVARS;COMPRESS;CORESHELL;DIELECTRIC;DIFFRACTION;DIPOLE;DPD-BASIC;DPD-MESO;DPD-REACT;DPD-SMOOTH;DRUDE;EFF;ELECTRODE;EXTRA-COMPUTE;EXTRA-DUMP;EXTRA-FIX;EXTRA-MOLECULE;EXTRA-PAIR;FEP;GRANULAR;INTERLAYER;KSPACE;LEPTON;MACHDYN;MANYBODY;MC;MEAM;MESONT;MISC;ML-IAP;ML-POD;ML-SNAP;MOFFF;MOLECULE;OPENMP;OPT;ORIENT;PERI;PHONON;PLUGIN;POEMS;QEQ;REACTION;REAXFF;REPLICA;RIGID;SHOCK;SPH;SPIN;SRD;TALLY;UEF;VORONOI;YAFF
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          Clang
      Version:       14.0.5
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_EXCEPTIONS;LAMMPS_OMP_COMPAT=4;LAMMPS_JPEG;LAMMPS_PNG;LAMMPS_GZIP;LAMMPS_FFMPEG;FFT_FFTW3;FFT_FFTW_THREADS;EIGEN_NO_CUDA;LAMMPS_ZSTD;LMP_OPENMP;LMP_PLUGIN
-- C compiler:       /usr/bin/cc
      Type:          Clang
      Version:       14.0.5
      C Flags:       -O2 -g -DNDEBUG
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Shared library flags:    
-- <<< MPI flags >>>
-- MPI_defines:      MPICH_SKIP_MPICXX;OMPI_SKIP_MPICXX;_MPICC_H
-- MPI includes:     /home/local/include
-- MPI libraries:    /home/local/lib/libmpicxx.so;/home/local/lib/libmpi.so;
-- <<< FFT settings >>>
-- Primary FFT lib:  FFTW3
-- Using double precision FFTs
-- Using threaded FFTs
-- <<< Building Tools >>>
-- <<< Building Unit Tests >>>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akohlmey/compile/lammps/build
```
Output from `lmp -h`:
```
Large-scale Atomic/Molecular Massively Parallel Simulator - 2 Aug 2023
Git info (develop / patch_2Aug2023)

Usage example: ./lmp -var t 300 -echo screen -in in.alloy

[...]

OS: FreeBSD "FreeBSD 13.2-RELEASE" 13.2-RELEASE amd64

Compiler: Clang C++ FreeBSD Clang 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c) with OpenMP 5.0
C++ standard: C++11
MPI v3.1: MPICH Version:        3.4.3
MPICH Release date:     Thu Dec 16 11:20:57 CST 2021
MPICH ABI:      13:12:1

Accelerator configuration:

OPENMP package API: OpenMP
OPENMP package precision: double

Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_EXCEPTIONS
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit

Available compression formats:

Extension: .gz     Command: gzip
Extension: .bz2    Command: bzip2
Extension: .zst    Command: zstd
Extension: .xz     Command: xz
Extension: .lzma   Command: xz
Extension: .lz4    Command: lz4


Installed packages:

AMOEBA ASPHERE BOCS BODY BPM BROWNIAN CG-DNA CG-SPICA CLASS2 COLLOID COLVARS 
COMPRESS CORESHELL DIELECTRIC DIFFRACTION DIPOLE DPD-BASIC DPD-MESO DPD-REACT 
DPD-SMOOTH DRUDE EFF ELECTRODE EXTRA-COMPUTE EXTRA-DUMP EXTRA-FIX 
EXTRA-MOLECULE EXTRA-PAIR FEP GRANULAR INTERLAYER KSPACE LEPTON MACHDYN 
MANYBODY MC MEAM MESONT MISC ML-IAP ML-POD ML-SNAP MOFFF MOLECULE OPENMP OPT 
ORIENT PERI PHONON PLUGIN POEMS QEQ REACTION REAXFF REPLICA RIGID SHOCK SPH 
SPIN SRD TALLY UEF VORONOI YAFF 
```

ctest summary:
```
100% tests passed, 0 tests failed out of 567

Label Time Summary:
noWindows    =   5.04 sec*proc (2 tests)
slow         =  93.27 sec*proc (68 tests)
unstable     =  49.81 sec*proc (46 tests)

Total Test time (real) = 191.79 sec
```

**Comment by akohlmey** [comment]
@yurivict I have tried many ways to reproduce this failure on multiple platforms (including a FreeBSD virtual machine) but have failed to do so. Can you please rerun the failing FileOperations test in the following two ways?
```
TEST_ARGS=-v ctest -R FileOperations -V
```
and
```
./test_file_operations -v
```
And report the full output. Please also provide the exact configuration command or attach your CMakeCache.txt file.
Thanks.

**Comment by akohlmey** [comment]
@yurivict I suspect that failure in the FileOperation unit test may be due to a problem in OpenMPI. 
Are you using MPICH or OpenMPI? I noticed that my VM uses MPICH. Same on my desktop.
Can you try setting the following environment variable `export OMPI_MCA_sharedfp="^sm"` and rerun the test?

**Comment by akohlmey** [comment]
I've further narrowed down the possible cause for the FileOperations to the MPIIO package. Please try testing without. We have been considering to remove it since it was sometimes broken and has been unmaintained for a long time.
