### ISSUE TITLE
No output from mpirun parallel execution

### ISSUE THREAD

**Issue by pietro-sillano** [lammps/lammps#3967]
**Summary**
I have freezed output (and simulation, no dump writing or any progress in log file) using mpirun command to lauch the lmp binary `mpirun -n 4 lmp -in in.lj` 

If i launch the serial job with `mpirun -n 1 lmp -in in.lj` works correctly

**LAMMPS Version and Platform**
LAMMPS (3 Aug 2023 - Development - patch_2Aug2023-747-ge655cda066)
OS: EndeavourOS Linux x86_64
Kernel: 6.5.9-arch2-1 
mpirun (Open MPI) 4.1.5

**Comment by akohlmey** [comment]
This is with the original in.lj benchmark input in the "bench" folder, right? or some modified input?
In the latter case, please provide the complete input deck including output.

This is unlikely due to LAMMPS, but more likely due to MPI and possibly some MPI setup issue. 

Can you try with: `mpirun --mca btl tcp,self  -np 4 lmp -in in.lj` ?

Sometimes additional information is available by adding `-nonbuf` or `-nb ` to the LAMMPS command line.

**Comment by pietro-sillano** [comment]
Yes, using the in.lj inside the bench folder. 
Also with your suggested command does not change anything. That's the output:
```
$ mpirun --mca btl tcp,self  -np 4 lmp_gpu -in in.lj -nonbuf
LAMMPS (15 Jun 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
```
I checked the version of MPI and it's 3.1. I installed openmpi package from arch repo. 

Recently I recompiled lammps to use as a python module and install mpi4py with pip but inside a virtual env

**Comment by akohlmey** [comment]
Please provide the output of `lmp -h`.

What happens, if you switch from `--mca btl tcp,self` to `--mca btl vader,self`?

**Comment by pietro-sillano** [comment]
output of `lmp -h`
```

Large-scale Atomic/Molecular Massively Parallel Simulator - 3 Aug 2023 - Development
Git info (develop / patch_2Aug2023-747-ge655cda066)

Usage example: lmp -var t 300 -echo screen -in in.alloy

List of command line options supported by this LAMMPS executable:

-echo none/screen/log/both  : echoing of input script (-e)
-help                       : print this help message (-h)
-in none/filename           : read input from file or stdin (default) (-i)
-kokkos on/off ...          : turn KOKKOS mode on or off (-k)
-log none/filename          : where to send log output (-l)
-mdi '<mdi flags>'          : pass flags to the MolSSI Driver Interface
-mpicolor color             : which exe in a multi-exe mpirun cmd (-m)
-cite                       : select citation reminder style (-c)
-nocite                     : disable citation reminder (-nc)
-nonbuf                     : disable screen/logfile buffering (-nb)
-package style ...          : invoke package command (-pk)
-partition size1 size2 ...  : assign partition sizes (-p)
-plog basename              : basename for partition logs (-pl)
-pscreen basename           : basename for partition screens (-ps)
-restart2data rfile dfile ... : convert restart to data file (-r2data)
-restart2dump rfile dgroup dstyle dfile ... 
                            : convert restart to dump file (-r2dump)
-reorder topology-specs     : processor reordering (-r)
-screen none/filename       : where to send screen output (-sc)
-skiprun                    : skip loops in run and minimize (-sr)
-suffix gpu/intel/opt/omp   : style suffix to apply (-sf)
-var varname value          : set index style variable (-v)

OS: Linux "EndeavourOS" 6.5.9-arch2-1 x86_64

Compiler: GNU C++ 13.2.1 20230801 with OpenMP 4.5
C++ standard: C++11
MPI v3.1: Open MPI v4.1.5, package: Open MPI builduser@chris-1 Distribution, ident: 4.1.5, repo rev: v4.1.5, Feb 23, 2023

Accelerator configuration:


Active compile time flags:

-DLAMMPS_GZIP
-DLAMMPS_PNG
-DLAMMPS_JPEG
-DLAMMPS_FFMPEG
-DLAMMPS_SMALLBIG
sizeof(smallint): 32-bit
sizeof(imageint): 32-bit
sizeof(tagint):   32-bit
sizeof(bigint):   64-bit

Available compression formats:

Extension: .gz     Command: gzip
Extension: .bz2    Command: bzip2
Extension: .zst    Command: zstd
Extension: .xz     Command: xz
Extension: .lzma   Command: xz
Extension: .lz4    Command: lz4


Installed packages:



List of individual style options included in this LAMMPS executable

* Atom styles:

atomic          body            charge          ellipsoid       hybrid          
line            sphere          tri             

* Integrate styles:

respa           verlet          

* Minimize styles:

cg              fire/old        fire            hftn            quickmin        
sd              

* Pair styles:

born            buck            buck/coul/cut   coul/cut        coul/debye      
coul/dsf        coul/wolf       reax            mesont/tpm      hybrid          
hybrid/overlay  hybrid/scaled   lj/cut          lj/cut/coul/cut lj/expand       
morse           soft            table           yukawa          zbl             
zero            

* Bond styles:

hybrid          zero            

* Angle styles:

hybrid          zero            

* Dihedral styles:

hybrid          zero            

* Improper styles:

hybrid          zero            

* KSpace styles:


* Fix styles

adapt           addforce        ave/atom        ave/chunk       ave/correlate   
ave/grid        ave/histo       ave/histo/weight                ave/time        
aveforce        balance         box/relax       deform          deposit         
ave/spatial     ave/spatial/sphere              lb/pc           
lb/rigid/pc/sphere              client/md       dt/reset        efield          
enforce2d       evaporate       external        gravity         halt            
heat            indent          langevin        lineforce       momentum        
move            nph             nph/sphere      npt             npt/sphere      
nve             nve/limit       nve/noforce     nve/sphere      nvt             
nvt/sllod       nvt/sphere      pair            planeforce      press/berendsen 
press/langevin  print           property/atom   recenter        restrain        
setforce        spring          spring/chunk    spring/self     store/force     
store/state     temp/berendsen  temp/rescale    thermal/conductivity            
vector          viscous         wall/harmonic   wall/lj1043     wall/lj126      
wall/lj93       wall/morse      wall/reflect    wall/region     wall/table      

* Compute styles:

aggregate/atom  angle           angle/local     angmom/chunk    bond            
bond/local      centro/atom     centroid/stress/atom            chunk/atom      
chunk/spread/atom               cluster/atom    cna/atom        com             
com/chunk       coord/atom      count/type      mesont          dihedral        
dihedral/local  dipole          dipole/chunk    displace/atom   erotate/sphere  
erotate/sphere/atom             fragment/atom   global/atom     group/group     
gyration        gyration/chunk  heat/flux       improper        improper/local  
inertia/chunk   ke              ke/atom         msd             msd/chunk       
omega/chunk     orientorder/atom                pair            pair/local      
pe              pe/atom         pressure        property/atom   property/chunk  
property/grid   property/local  rdf             reduce          reduce/chunk    
reduce/region   slice           stress/atom     temp            temp/chunk      
temp/com        temp/deform     temp/partial    temp/profile    temp/ramp       
temp/region     temp/sphere     torque/chunk    vacf            vcm/chunk       

* Region styles:

block           cone            cylinder        ellipsoid       intersect       
plane           prism           sphere          union           

* Dump styles:

atom            cfg             custom          atom/mpiio      cfg/mpiio       
custom/mpiio    xyz/mpiio       grid            grid/vtk        image           
local           movie           xyz             

* Command styles

angle_write     balance         change_box      create_atoms    create_bonds    
create_box      delete_atoms    delete_bonds    box             kim_init        
kim_interactions                kim_param       kim_property    kim_query       
reset_ids       reset_atom_ids  reset_mol_ids   message         server          
dihedral_write  displace_atoms  info            minimize        read_data       
read_dump       read_restart    replicate       rerun           run             
set             velocity        write_coeff     write_data      write_dump      
write_restart   

```

using `mpirun --mca btl vader,self -np 4 lmp -in in.lj` still nothing

**Comment by akohlmey** [comment]
I am drawing a blank as to what could be happening. Have you tried compiling and running some other MPI program?

**Comment by akohlmey** [comment]
If I had physical access to the machine, I would compile a LAMMPS binary with debug info included, launch the calculation, identify the process IDs and attach a debugger to each of them with `gdb -p <pid>` and then try to find out where exactly they get stuck.

**Comment by pietro-sillano** [comment]
I have access to the machine (it is my laptop) and I would try with gdb but I think this is far above my skills

**Comment by akohlmey** [comment]
Please see: https://docs.lammps.org/Errors_debug.html

You start a run and from a second terminal you can determine the process IDs with top or pstree and then launch `gdb -p <pid> to attache to one of them. Then type "where" as shown in the LAMMPS manual to get the stack trace. Copy the stack trace and exit with CTRL-D.

You can try with the other process IDs to see, if the run gets stuck in different places on them.

**Comment by pietro-sillano** [comment]
this is the output of gdb of the rank 0 process
```
Attaching to process 12586
[New LWP 12590]
[New LWP 12592]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]                                                
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fd567d20f6f in __GI___poll (fds=fds@entry=0x55ff7d3bf440, nfds=nfds@entry=4, 
    timeout=timeout@entry=0) at ../sysdeps/unix/sysv/linux/poll.c:29
29        return SYSCALL_CANCEL (poll, fds, nfds, timeout);                                  
(gdb) where
#0  0x00007fd567d20f6f in __GI___poll (fds=fds@entry=0x55ff7d3bf440, nfds=nfds@entry=4, 
    timeout=timeout@entry=0) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fd567a0b96a in poll (__timeout=<optimized out>, __nfds=4, __fds=0x55ff7d3bf440)
    at /usr/include/bits/poll2.h:39
#2  poll_dispatch (base=0x55ff7d1d16b0, tv=0x7fff608295b0)
    at /usr/src/debug/libevent/libevent-2.1.12-stable/poll.c:182
#3  0x00007fd567a08185 in event_base_loop (base=0x55ff7d1d16b0, flags=2)
    at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1992
#4  0x00007fd567ba600d in opal_progress_events () at runtime/opal_progress.c:191
#5  opal_progress_events.isra.0 () at runtime/opal_progress.c:172
#6  0x00007fd567b588e4 in opal_progress () at runtime/opal_progress.c:247
#7  0x00007fd5682e62ce in sync_wait_st (sync=<optimized out>)
    at ../opal/threads/wait_sync.h:83
#8  ompi_request_default_wait_all (count=<optimized out>, requests=0x55ff7d416640, 
    statuses=0x0) at request/req_wait.c:234
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x00007fd56833f125 in ompi_coll_base_bcast_intra_generic (
    buffer=buffer@entry=0x7fff6082991c, original_count=original_count@entry=1, 
    datatype=datatype@entry=0x7fd5683a1600 <ompi_mpi_int>, root=root@entry=0, 
    comm=comm@entry=0x55ff7c2160e0 <ompi_mpi_comm_world>, 
    module=module@entry=0x55ff7d3e4ff0, count_by_segment=1, tree=0x55ff7d4165a0)
    at mca/coll/base/coll_base_bcast.c:98
#10 0x00007fd56833f553 in ompi_coll_base_bcast_intra_bintree (buffer=0x7fff6082991c, 
    count=1, datatype=0x7fd5683a1600 <ompi_mpi_int>, root=0, 
    comm=0x55ff7c2160e0 <ompi_mpi_comm_world>, module=0x55ff7d3e4ff0, segsize=0)
    at mca/coll/base/coll_base_bcast.c:272
#11 0x00007fd565446ea1 in ompi_coll_tuned_bcast_intra_dec_fixed (buff=<optimized out>, 
    count=<optimized out>, datatype=<optimized out>, root=<optimized out>, 
    comm=<optimized out>, module=<optimized out>)
    at /usr/src/debug/openmpi/openmpi-4.1.5/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:649
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x00007fd5682f5b78 in PMPI_Bcast (buffer=0x7fff6082991c, count=1, 
    datatype=0x7fd5683a1600 <ompi_mpi_int>, root=0, 
    comm=0x55ff7c2160e0 <ompi_mpi_comm_world>) at mpi/c/profile/pbcast.c:114
#13 0x000055ff7bc75fc7 in LAMMPS_NS::Input::file (this=0x55ff7d36f770)
    at /home/pietro/Desktop/software_source/lammps/src/input.cpp:285
#14 0x000055ff7bc67b9d in main (argc=<optimized out>, argv=<optimized out>)
    at /home/pietro/Desktop/software_source/lammps/src/main.cpp:77
 ```
this is the second process
```
Attaching to process 12587
[New LWP 12593]
[New LWP 12595]
This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) 
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fec62120f6f in poll () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007fec62120f6f in poll () from /usr/lib/libc.so.6
#1  0x00007fec624b196a in ?? () from /usr/lib/libevent_core-2.1.so.7
#2  0x00007fec624ae185 in event_base_loop () from /usr/lib/libevent_core-2.1.so.7
#3  0x00007fec61fe800d in ?? () from /usr/lib/libopen-pal.so.40
#4  0x00007fec61f9a8e4 in opal_progress () from /usr/lib/libopen-pal.so.40
#5  0x00007fec627c3c76 in ompi_request_default_wait () from /usr/lib/libmpi.so.40
#6  0x00007fec6281d2bb in ompi_coll_base_bcast_intra_generic () from /usr/lib/libmpi.so.40
#7  0x00007fec6281d553 in ompi_coll_base_bcast_intra_bintree () from /usr/lib/libmpi.so.40
#8  0x00007fec60030ea1 in ompi_coll_tuned_bcast_intra_dec_fixed ()
   from /usr/lib/openmpi/mca_coll_tuned.so
#9  0x00007fec627d3b78 in PMPI_Bcast () from /usr/lib/libmpi.so.40
#10 0x000055d974103fc7 in LAMMPS_NS::Input::file (this=0x55d975f1d760)
    at /home/pietro/Desktop/software_source/lammps/src/input.cpp:285
#11 0x000055d9740f5b9d in main (argc=<optimized out>, argv=<optimized out>)
    at /home/pietro/Desktop/software_source/lammps/src/main.cpp:77
(gdb) 
```

**Comment by akohlmey** [comment]
This confirms my suspicion. There is something broken with your MPI library or how it is used. The line where it gets stuck is the first communication where the input text is broadcast line by line from rank 0 to the other MPI processes.

You could disconnect your laptop from the net, temporarily take down the firewall and try again to see, if there is something blocking communication (and then put the firewall back up before reconnecting).

Another option would be to uninstall OpenMPI and try out MPICH.

This is not a LAMMPS issue.

**Comment by pietro-sillano** [comment]
Okay, I only disconnect from the net and now it works, I am quite surprised! How the network connectivity should influence openmpi?

**Comment by akohlmey** [comment]
> How the network connectivity should influence openmpi?

OpenMPI may use TCP/IP to identify nodes or send data.
There could be some routing or firewall issue that is blocking such data or the address lookup or sending data to non-existing locations. The cause for that could be manifold. If I could tell from remote, I would open a business and and get rich by solving such problems for lazy IT people at companies with deep pockets. ;-)

**Comment by pietro-sillano** [comment]
Thank you for your answer and your patience! your work is precious :)
