### ISSUE TITLE
pylammps thermo_style issue

### ISSUE THREAD

**Issue by gideonsimpson** [lammps/lammps#701]
I’ve been trying my hand at rewriting some examples using PyLammps, and I have the following difficulty with my rewrite of USER/DIFFUSE/in.msd.2d which makes an estimate of the mean square displacement.  The following is giving me trouble:

If I use the lines
```
L.compute("msd", "all", "msd", "com", "yes")
L.variable("msd", "equal", "c_msd[4]")
L.thermo_style("custom","step", "v_msd")
```
it works as expected, but
```
L.compute("msd", "all", "msd", "com", "yes")
L.thermo_style("custom","step", “c_msd[4]")
```
generates the error
```
Traceback (most recent call last):
  File "msd2d.py", line 51, in <module>
    L.run(10000)
  File "/opt/lammps/python/lammps.py", line 689, in run
    self.runs += get_thermo_data(output)
  File "/opt/lammps/python/lammps.py", line 633, in get_thermo_data
    thermo_data = namedtuple('ThermoData', list(current_run.keys()))(*list(current_run.values()))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 351, in namedtuple
    'alphanumeric characters and underscores: %r' % name)
ValueError: Type names and field names can only contain alphanumeric characters and underscores: 'c_msd[4]'
```
This is occurring with August 2017 LAMMPS. The complete python code is:
```
from lammps import IPyLammps


L=IPyLammps()

L.variable("x", "equal", 40)
L.variable("y", "equal", 40)

L.variable("rho", "equal", 0.6)
L.variable("t", "equal", 1.0)
L.variable("rc", "equal", 2.5)

x = L.variables['x']
y = L.variables['y']
rho = L.variables['rho']
t = L.variables['t']
rc = L.variables['rc']

L.units("lj")
L.dimension(2)
L.atom_style("atomic")
L.neigh_modify("delay", 0, "every", 1)

L.lattice("sq2", rho.value)
L.region("simbox", "block", 0, x.value, 0, y.value, -0.1, 0.1)
L.create_box(1, "simbox")
L.create_atoms(1, "box")

L.pair_style("lj/cut", rc.value)
L.pair_coeff("*", "*", 1., 1.)

L.mass("*", 1.0)
L.velocity("all", "create", t.value, 97287)

# equilibration run
L.fix(1, "all", "nve")
L.fix(2, "all", "langevin", t.value, t.value, 0.1, 498094)
L.fix(3, "all","enforce2d")

L.thermo(100)
L.run(500)

L.unfix(2)
L.reset_timestep(0)

# set up MSD computation for online run
L.compute("msd", "all", "msd", "com", "yes")
L.variable("msd", "equal", "c_msd[4]")
#L.thermo_style("custom","step", "c_msd[4]")
L.thermo_style("custom","step", "v_msd")
L.thermo(100)
L.run(1000)

```

**Comment by rbberger** [comment]
@gideonsimpson The bugfix I just submitted should solve your issue.
